### ISSUE TITLE
No module "enterprise_edition" in kong-pdk >= 0.34

### ISSUE THREAD

**Issue by vtlkvl** [Kong/kong-python-pdk#124]
I'm not able to get the latest PDK version working. https://github.com/Kong/kong-python-pdk/pull/114 seems to have broken PDK - the usage of `kong_pdk.pdk.kong.enterprise_edition` has been added, but `enterprise_edition` is not packaged. As a result plugins fail to load with `No module named 'kong_pdk.pdk.kong.enterprise_edition'`.

@StarlightIbuki @fffonion I'm not sure what is the right way to fix it. Would you please advise?

**Comment by fkbarrett** [comment]
Same issue here. We want to get the memory leak fix in 0.35 but can't upgrade.

**Comment by vtlkvl** [comment]
@StarlightIbuki @fffonion Any updates on this?

**Comment by StarlightIbuki** [comment]
@vtlkvl @fkbarrett Sorry for the confusion. We were trying to unify the community version and enterprise version of PDK support and it causes this issue. We're discussing a solution and the most likely one would be to revert the change...
