### ISSUE TITLE
Release of 0.3.0

### ISSUE THREAD

**Issue by ingvaldlorentzen** [Kong/kong-python-pdk#47]
Could we get a PyPI release of the `0.3.0` version?

I see the code includes the new vault features included in [Kong Gateway 2.8.0.0](https://docs.konghq.com/gateway/changelog/) which might make my issue #45 unnecessary for my use case.

**Comment by fffonion** [comment]
Hi @ingvaldlorentzen , it's actually `0.3` but as it's not semver, pip regarded as it's smaller than `0.27`. I re-released a `0.30` which should be picked up by `pip`.

**Comment by ingvaldlorentzen** [comment]
Awesome! Thank you
