### ISSUE TITLE
Performance Difference between Plugins developed by python-pdk and Lua based plugins

### ISSUE THREAD

**Issue by rohan-97** [Kong/kong-python-pdk#6]
Hey Guys,

I am fairly new to Kong Gateway and was planning to integrate kong OSS in my application as a API gateway.

My application is mostly build on python3 so I was planning to implement few additional authentication mechanism plugin using kong-python-pdk

I wanted to know from performance point of view is there any downgrade of performance if the custom plugins are build on python3 rather than Lua?

are there any performance tests done or reports available

Thanks in advance

**Comment by fffonion** [comment]
Hi @rohan-97 , the performance drop is highly related to how many PDK calls you invoked in your Python plugin. As external
plugins talks to Kong through network RPC and is faily heavy. I would say the downgrade of performance is noticable.
But I don't have exact numbers yet, I will post here when results are available.

**Comment by rohan-97** [comment]
Thanks @fffonion for the information!
