### ISSUE TITLE
When using with Docker Compose - Python not found

### ISSUE THREAD

**Issue by olliegg123** [Kong/kong-python-pdk#8]
I think I'm probably missing something, but when using the demo scripts and trying to use docker compose up on a DB-less instance of kong, docker can't find Python3. What am I doing wrong?

**Comment by fffonion** [comment]
Hi @olliegg123 , which demo scripts are you using?

**Comment by olliegg123** [comment]
I'm trying to use py-hello.py but I think I'm probably missing something in my declarative config. 

But I've got the example statements in the repo included.

**Comment by fffonion** [comment]
That depend on which docker image you are using, with `alpine` or `kong-<version>` without distro (default to alpine), I think you need to install python3 from the package manager (apk update && apk add python3).
Do note the image is set to run with non-root user. You will need to build a sub image to add the python3.

**Comment by fffonion** [comment]
Closing as the issue seems be environment related. Please re-open if the issue persists.
