### ISSUE TITLE
Unable to set QueryString in Custom Plugin access phase

### ISSUE THREAD

**Issue by sivasubramani300890** [Kong/kong-python-pdk#92]
Hi Team,
I am trying to get query string using "kong.request.get_raw_query()" and after changing to right values setting the query string using "kong.service.request.set_raw_query(queryString)".But it is not happening.

Using python to develop third party plugin

**Comment by fffonion** [comment]
Hi @sivasubramani300890 `kong.request` and `kong.service.request` are two different objects,
the former is what Kong sees from client request, the later is what upstream ("Service") sees from Kong's request

```
client --------------> kong -------------> upstream
             ^                                   ^
        kong.request                 kong.service.request
```

**Comment by fffonion** [comment]
@sivasubramani300890 might consider use `kong.service.request.set_raw_query` to set query instead of
the path.

**Comment by sivasubramani300890** [comment]
Hi @fffonion ,Thanks for the response.set_path is working fine but it was not working earlier.Anyway Thanks for quick response
